apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: test-backend
          image: thilina123/test-backend:b0436c5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080